services:

  redis:
    container_name: redis-cache
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - local
    depends_on:
      - mssql
    deploy:
      resources:
        limits:
          memory: 512M # Limita a memória a 512MB
        reservations:
          memory: 256M # Reserva 256MB de memória
    volumes:
      - ./path/to/local/dаta:/root/redis
      - ./path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"] # Configura a política de memória no Redis
    environment:
      - REDIS_PASSWORD=P@ssw0rd
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'P@ssw0rd'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1433:1433"
    networks:
      - local
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
      - ./setup.sql:/var/opt/mssql/scripts/setup.sql
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 60 && 
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -i /var/opt/mssql/scripts/setup.sql && 
      wait
      "
  
  web-api:
    image: matteusmachhado/webapi-with-redis
    container_name: webapi
    build:
      context: ../
      dockerfile: ./src/Project.WebApi/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5001
    networks:
      - local
    depends_on:
      - mssql
      - redis

networks:
  local: